language: cpp

jobs:
  include:
    # macOS: 10.15.
    - os: osx
      osx_image: xcode11.5
      env: BAZEL_VERSION=3.0.0
    - os: osx
      osx_image: xcode11.5
      env: BAZEL_VERSION=0.29.1
    # Ubuntu Linux 18.04 and clang 7.
    - os: linux
      dist: bionic
      compiler: clang
      env: BAZEL_VERSION=3.0.0
    - os: linux
      dist: bionic
      compiler: clang
      env: BAZEL_VERSION=0.29.1
    # Ubuntu Linux 18.04 and GCC 7.4.0.
    - os: linux
      dist: bionic
      compiler: gcc
      env: BAZEL_VERSION=3.0.0
    - os: linux
      dist: bionic
      compiler: gcc
      env: BAZEL_VERSION=0.29.1

before_install:
  - OS=linux
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then OS=darwin; fi
  # Install Bazel.
  - GH_BASE="https://github.com/bazelbuild/bazel/releases/download/$BAZEL_VERSION"
  - GH_ARTIFACT="bazel-$BAZEL_VERSION-installer-$OS-x86_64.sh"
  - CI_BASE="http://ci.bazel.io/job/Bazel/JAVA_VERSION=1.8,PLATFORM_NAME=$OS-x86_64/lastSuccessfulBuild/artifact/output/ci"
  - CI_ARTIFACT="bazel--installer.sh"
  - URL="$GH_BASE/$GH_ARTIFACT"
  - if [[ "$BAZEL_VERSION" == "HEAD" ]]; then CI_ARTIFACT="`wget -qO- $CI_BASE | grep
    -o 'bazel-[-_a-zA-Z0-9\.]*-installer.sh' | uniq`"; fi
  - if [[ "$BAZEL_VERSION" == "HEAD" ]]; then URL="$CI_BASE/$CI_ARTIFACT"; fi
  - echo $URL
  - wget -O install.sh $URL
  - chmod +x install.sh
  - "./install.sh --user"
  - rm -f install.sh

before_script:
  # Print some LLVM config options that are useful for debugging.
  - bazel run //10.0.0:llvm-config -- --system-libs  | tr ' ' '\n' | sed '/^$/d ;s/^/    "/ ; s/$/",/'
  - bazel run //10.0.0:llvm-config -- --cxxflags  | tr ' ' '\n' | sed '/^$/d ;s/^/    "/ ; s/$/",/'
  - bazel run //10.0.0:llvm-config -- --ldflags  | tr ' ' '\n' | sed '/^$/d ;s/^/    "/ ; s/$/",/'
  - bazel run //10.0.0:llvm-config -- --libs  | tr ' ' '\n' | sed '/^$/d ;s/^/    "/ ; s/$/",/'

script:
  # Run the tests.
  - bazel test //... --keep_going --sandbox_debug --verbose_failures  --test_output=errors
